services:
    quickdrop:
        image: roastslav/quickdrop:latest
        ports:
            - 8080:8080
        environment:
            - TZ=Etc/UTC
        volumes:
            - ./db:/app/db
            - ./db-backups:/app/db-backups
            - ./log:/app/log
            - ./files:/app/files
            - ./branding:/app/branding
            - ./reputation-feeds:/app/reputation-feeds
        restart: unless-stopped
