name: Feature request
description: Suggest an idea / improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: I'm willing to implement this (or help)
        - label: This needs discussion before implementation
